from __future__ import annotations

from pathlib import Path
import os
import textwrap
import time

import typer

from .config import Settings
from .fixer import doctor_patch, fix_issue
from .github_ops import (
    clone_repo,
    commit_all,
    create_branch,
    create_pr,
    ensure_gh_installed,
    ensure_git_installed,
    get_issue,
    list_open_issues,
    push_branch,
    repo_slug_from_url,
)
from .shell import run

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="CLI backend that finds GitHub issues, applies an automated fix, and opens a PR.",
)


@app.command("doctor")
def doctor() -> None:
    """Run preflight checks for local environment setup."""
    failures = 0

    def ok(msg: str) -> None:
        typer.echo(f"[OK] {msg}")

    def fail(msg: str) -> None:
        nonlocal failures
        failures += 1
        typer.echo(f"[FAIL] {msg}")

    try:
        ensure_git_installed()
        ok("git is installed")
    except RuntimeError as exc:
        fail(str(exc))

    gh_bin = os.getenv("AUTOFIX_GH_BIN", "gh")
    gh_available = False
    try:
        ensure_gh_installed()
        ok(f"GitHub CLI is installed and valid ({gh_bin})")
        gh_available = True
    except RuntimeError as exc:
        fail(str(exc))

    if gh_available:
        auth = run([gh_bin, "auth", "status"], check=False)
        if auth.returncode == 0:
            ok("GitHub CLI auth is configured")
        else:
            fail("GitHub CLI auth is not configured. Run: gh auth login")

    if os.getenv("OPENAI_API_KEY"):
        ok("OPENAI_API_KEY is set")
    else:
        fail("OPENAI_API_KEY is not set")

    if failures:
        raise typer.Exit(code=1)
    typer.echo("All checks passed.")


@app.command("doctor-patch")
def doctor_patch_command(
    repo_dir: Path = typer.Option(
        Path("."),
        "--repo-dir",
        help="Git repository path where synthetic patch check is executed.",
    ),
    create_pull_request: bool = typer.Option(
        True,
        "--create-pr/--no-create-pr",
        help="Whether to commit probe patch, push branch, and create a PR.",
    ),
) -> None:
    """Validate git patch parsing/apply and optionally open a PR."""
    repo = repo_dir.resolve()
    try:
        if not create_pull_request:
            doctor_patch(repo, keep_changes=False)
            typer.echo("[OK] Synthetic patch check passed.")
            typer.echo("No commit/PR created (--no-create-pr).")
            return

        ensure_gh_installed()
        remote = run(
            ["git", "config", "--get", "remote.origin.url"], cwd=repo, check=False
        ).stdout.strip()
        if not remote:
            raise RuntimeError("Could not read remote.origin.url from target repository.")
        slug = repo_slug_from_url(remote)

        branch = f"autofix/doctor-patch-{int(time.time())}"
        run(["git", "checkout", "-B", branch], cwd=repo)
        result = doctor_patch(repo, keep_changes=True)

        commit_all(repo, "chore: add doctor patch probe")
        push_branch(repo, branch)
        pr_title = "Doctor patch probe"
        pr_body = textwrap.dedent(
            f"""
            ## What
            - Added a temporary synthetic patch probe file to verify patch pipeline.
            - Probe file: `{result.probe_name}`

            ## Why
            - Validate git apply + branch + PR path in this repository.

            _Generated by autofix doctor-patch._
            """
        ).strip()
        pr_url = create_pr(slug, pr_title, pr_body, head_branch=branch)
        typer.echo("[OK] Synthetic patch check passed.")
        typer.echo(f"PR created: {pr_url}")
    except RuntimeError as exc:
        typer.echo(f"[FAIL] {exc}")
        raise typer.Exit(code=1) from exc


@app.command("run")
def run_pipeline(
    repo_url: str = typer.Argument(..., help="GitHub repository URL."),
    issue_number: int | None = typer.Option(
        None, "--issue", "-i", help="Specific issue number. Defaults to first open issue."
    ),
    workspace: Path = typer.Option(
        Path(".autofix-workspace"),
        "--workspace",
        "-w",
        help="Directory where target repositories are cloned.",
    ),
    create_pull_request: bool = typer.Option(
        True,
        "--create-pr/--no-create-pr",
        help="Whether to push branch and create a pull request.",
    ),
    fallback_synthetic_pr: bool = typer.Option(
        True,
        "--fallback-synthetic-pr/--no-fallback-synthetic-pr",
        help="If issue fix fails, create a synthetic probe PR instead of failing.",
    ),
) -> None:
    """Run issue-to-fix-to-PR flow from the CLI."""
    started_at = time.monotonic()

    def progress(message: str) -> None:
        elapsed = time.monotonic() - started_at
        typer.echo(f"[{elapsed:6.1f}s] {message}")

    settings = Settings.from_env(workspace=workspace)
    slug = repo_slug_from_url(repo_url)

    progress(f"Cloning/updating {slug}")
    repo_dir = clone_repo(repo_url, settings.workspace)

    if issue_number is None:
        progress("Listing open issues")
        issues = list_open_issues(slug, limit=20)
        if not issues:
            raise typer.BadParameter("No open issues found.")
        selected = issues[0]
        issue_number = selected.number
        progress(f"Selected issue #{selected.number}: {selected.title}")

    progress(f"Loading issue #{issue_number}")
    issue = get_issue(slug, issue_number)
    branch = create_branch(repo_dir, issue.number)
    progress(f"Working on branch {branch}")

    used_fallback_pr = False
    fix_error: RuntimeError | None = None
    fix_result = None
    try:
        fix_result = fix_issue(repo_dir, issue, settings, progress=progress)
        commit_message = f"fix: resolve issue #{issue.number} - {issue.title}"
        progress("Committing changes")
        commit_all(repo_dir, commit_message)
    except RuntimeError as exc:
        fix_error = exc
        if not create_pull_request or not fallback_synthetic_pr:
            raise
        used_fallback_pr = True
        progress("Issue fix failed, creating synthetic fallback patch")
        probe = doctor_patch(repo_dir, keep_changes=True)
        commit_message = (
            f"chore: doctor fallback for issue #{issue.number} (autofix pipeline)"
        )
        progress("Committing synthetic fallback patch")
        commit_all(repo_dir, commit_message)

    pr_url = ""
    if create_pull_request:
        progress("Pushing branch")
        push_branch(repo_dir, branch)
        if used_fallback_pr:
            pr_title = f"Fallback PR for #{issue.number}: {issue.title}"
            pr_body = textwrap.dedent(
                f"""
                ## What
                - Automated fix generation failed for #{issue.number}.
                - Created synthetic probe patch as fallback to validate PR pipeline.
                - Probe file: `{probe.probe_name}`

                ## Source issue
                - {issue.url}

                ## Failure details
                ```
                {fix_error}
                ```

                _Generated by autofix CLI fallback mode._
                """
            ).strip()
        else:
            pr_title = f"Fix #{issue.number}: {issue.title}"
            pr_body = textwrap.dedent(
                f"""
                ## What
                - Automated fix for #{issue.number}
                - Source issue: {issue.url}

                ## Validation
                ```
                {fix_result.validation_log}
                ```

                _Generated by autofix CLI._
                """
            ).strip()
        progress("Creating pull request")
        pr_url = create_pr(slug, pr_title, pr_body, head_branch=branch)
        progress(f"PR created: {pr_url}")
    else:
        progress("Skipping PR creation (--no-create-pr)")

    progress("Done")
    if fix_result and fix_result.validation_log:
        typer.echo("\nValidation output:")
        typer.echo(fix_result.validation_log)
    if pr_url:
        typer.echo(f"\nPull request URL: {pr_url}")


if __name__ == "__main__":
    app()
