from __future__ import annotations

from pathlib import Path
import textwrap

import typer

from .config import Settings
from .fixer import fix_issue
from .github_ops import (
    clone_repo,
    commit_all,
    create_branch,
    create_pr,
    get_issue,
    list_open_issues,
    push_branch,
    repo_slug_from_url,
)

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="CLI backend that finds GitHub issues, applies an automated fix, and opens a PR.",
)


@app.command("run")
def run_pipeline(
    repo_url: str = typer.Argument(..., help="GitHub repository URL."),
    issue_number: int | None = typer.Option(
        None, "--issue", "-i", help="Specific issue number. Defaults to first open issue."
    ),
    workspace: Path = typer.Option(
        Path(".autofix-workspace"),
        "--workspace",
        "-w",
        help="Directory where target repositories are cloned.",
    ),
    create_pull_request: bool = typer.Option(
        True,
        "--create-pr/--no-create-pr",
        help="Whether to push branch and create a pull request.",
    ),
) -> None:
    """Run issue-to-fix-to-PR flow from the CLI."""
    settings = Settings.from_env(workspace=workspace)
    slug = repo_slug_from_url(repo_url)

    typer.echo(f"Cloning/updating {slug}...")
    repo_dir = clone_repo(repo_url, settings.workspace)

    if issue_number is None:
        issues = list_open_issues(slug, limit=20)
        if not issues:
            raise typer.BadParameter("No open issues found.")
        selected = issues[0]
        issue_number = selected.number
        typer.echo(f"Selected issue #{selected.number}: {selected.title}")

    issue = get_issue(slug, issue_number)
    branch = create_branch(repo_dir, issue.number)
    typer.echo(f"Working on branch {branch}")

    fix_result = fix_issue(repo_dir, issue, settings)
    commit_message = f"fix: resolve issue #{issue.number} - {issue.title}"
    commit_all(repo_dir, commit_message)

    pr_url = ""
    if create_pull_request:
        push_branch(repo_dir, branch)
        pr_title = f"Fix #{issue.number}: {issue.title}"
        pr_body = textwrap.dedent(
            f"""
            ## What
            - Automated fix for #{issue.number}
            - Source issue: {issue.url}

            ## Validation
            ```
            {fix_result.validation_log}
            ```

            _Generated by autofix CLI._
            """
        ).strip()
        pr_url = create_pr(slug, pr_title, pr_body)
        typer.echo(f"PR created: {pr_url}")
    else:
        typer.echo("Skipping PR creation (--no-create-pr).")

    typer.echo("Done.")
    if fix_result.validation_log:
        typer.echo("\nValidation output:")
        typer.echo(fix_result.validation_log)
    if pr_url:
        typer.echo(f"\nPull request URL: {pr_url}")


if __name__ == "__main__":
    app()
